### ISSUE TITLE
Add fleet UI components

### ISSUE THREAD

**Issue by chfritz** [transitiverobotics/transact#32]
Many Transitive capabilities also provide a fleet UI component. For instance, webrtc-video lists past sessions, health-monitoring provides a general health overview of the fleet, and config-management provides a mechanism to set fleet-wide default config values. We also want to show off these.

Not sure where best to put them yet.

**Comment by jlurgo** [comment]
An option would be to have a (default) "whole fleet" option in the device selector for each capability section.
With that one selected we would show the fleet widget
We can show it only for fleet enabled capabilities

**Comment by chfritz** [comment]
It's an option. But it might be confusing to the user to see "fleet" in the device selector and also the result of selecting "fleet" vs. a specific device is very different.

Another options might be to put it on the Devices page, because that one already lists the whole fleet. Would it make sense to put an accordion underneath with one panel per capability showing the respective fleet widget?

**Comment by jlurgo** [comment]
Yes, makes sense, I can start working on it RN
